# Generated by Django 2.2.4 on 2019-09-02 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departaments',
            fields=[
                ('dept_no', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('emp_no', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('hire_date', models.DateTimeField(verbose_name='fecha de contrato')),
            ],
        ),
        migrations.CreateModel(
            name='titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('from_date', models.DateTimeField(verbose_name='fecha de')),
                ('to_date', models.DateTimeField(verbose_name='fecha hasta')),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.employees')),
            ],
        ),
        migrations.CreateModel(
            name='salaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('from_date', models.DateTimeField(verbose_name='fecha de')),
                ('to_date', models.DateTimeField(verbose_name='fecha hasta')),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.employees')),
            ],
        ),
        migrations.CreateModel(
            name='dept_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(verbose_name='fecha de')),
                ('to_date', models.DateTimeField(verbose_name='fecha hasta')),
                ('dept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.departaments')),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.employees')),
            ],
        ),
        migrations.CreateModel(
            name='dept_emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(verbose_name='fecha de')),
                ('to_date', models.DateTimeField(verbose_name='fecha hasta')),
                ('dept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.departaments')),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.employees')),
            ],
        ),
    ]
