# Generated by Django 2.2.4 on 2019-09-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departaments',
            options={'ordering': ['dept_no'], 'verbose_name': 'departament', 'verbose_name_plural': 'departaments'},
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ['title'], 'verbose_name': 'titles', 'verbose_name_plural': 'title'},
        ),
    ]
