# Generated by Django 2.2.4 on 2019-09-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0002_auto_20190902_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departaments',
            options={'ordering': ['dept_name'], 'verbose_name': 'departament', 'verbose_name_plural': 'departaments'},
        ),
    ]
