# Generated by Django 2.2.4 on 2019-09-02 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followerId', models.BigIntegerField()),
                ('followedId', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hastag',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('hastag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user_status_updates',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('date', models.DateField(verbose_name='fecha de modificacion')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redsocial.user')),
            ],
        ),
        migrations.CreateModel(
            name='user_status_updates_hastags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hastag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redsocial.hastag')),
                ('user_status_updates_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redsocial.user_status_updates')),
            ],
        ),
        migrations.CreateModel(
            name='user_status_update_comments',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('date', models.DateField(verbose_name='fecha de la seccion de comentarios')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redsocial.user')),
                ('user_status_update_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redsocial.user_status_updates')),
            ],
        ),
    ]
